# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drone/Code/DroneController

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drone/Code/DroneController

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drone/Code/DroneController/CMakeFiles /home/drone/Code/DroneController//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drone/Code/DroneController/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DroneController

# Build rule for target.
DroneController: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DroneController
.PHONY : DroneController

# fast build rule for target.
DroneController/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/build
.PHONY : DroneController/fast

#=============================================================================
# Target rules for targets named libsbus

# Build rule for target.
libsbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libsbus
.PHONY : libsbus

# fast build rule for target.
libsbus/fast:
	$(MAKE) $(MAKESILENT) -f libserial/src/CMakeFiles/libsbus.dir/build.make libserial/src/CMakeFiles/libsbus.dir/build
.PHONY : libsbus/fast

Connector.o: Connector.cpp.o
.PHONY : Connector.o

# target to build an object file
Connector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/Connector.cpp.o
.PHONY : Connector.cpp.o

Connector.i: Connector.cpp.i
.PHONY : Connector.i

# target to preprocess a source file
Connector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/Connector.cpp.i
.PHONY : Connector.cpp.i

Connector.s: Connector.cpp.s
.PHONY : Connector.s

# target to generate assembly for a file
Connector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/Connector.cpp.s
.PHONY : Connector.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/main.cpp.s
.PHONY : main.cpp.s

raspberry-sbus/src/decoder/DecoderFSM.o: raspberry-sbus/src/decoder/DecoderFSM.cpp.o
.PHONY : raspberry-sbus/src/decoder/DecoderFSM.o

# target to build an object file
raspberry-sbus/src/decoder/DecoderFSM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/decoder/DecoderFSM.cpp.o
.PHONY : raspberry-sbus/src/decoder/DecoderFSM.cpp.o

raspberry-sbus/src/decoder/DecoderFSM.i: raspberry-sbus/src/decoder/DecoderFSM.cpp.i
.PHONY : raspberry-sbus/src/decoder/DecoderFSM.i

# target to preprocess a source file
raspberry-sbus/src/decoder/DecoderFSM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/decoder/DecoderFSM.cpp.i
.PHONY : raspberry-sbus/src/decoder/DecoderFSM.cpp.i

raspberry-sbus/src/decoder/DecoderFSM.s: raspberry-sbus/src/decoder/DecoderFSM.cpp.s
.PHONY : raspberry-sbus/src/decoder/DecoderFSM.s

# target to generate assembly for a file
raspberry-sbus/src/decoder/DecoderFSM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/decoder/DecoderFSM.cpp.s
.PHONY : raspberry-sbus/src/decoder/DecoderFSM.cpp.s

raspberry-sbus/src/decoder/packet_decoder.o: raspberry-sbus/src/decoder/packet_decoder.c.o
.PHONY : raspberry-sbus/src/decoder/packet_decoder.o

# target to build an object file
raspberry-sbus/src/decoder/packet_decoder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/decoder/packet_decoder.c.o
.PHONY : raspberry-sbus/src/decoder/packet_decoder.c.o

raspberry-sbus/src/decoder/packet_decoder.i: raspberry-sbus/src/decoder/packet_decoder.c.i
.PHONY : raspberry-sbus/src/decoder/packet_decoder.i

# target to preprocess a source file
raspberry-sbus/src/decoder/packet_decoder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/decoder/packet_decoder.c.i
.PHONY : raspberry-sbus/src/decoder/packet_decoder.c.i

raspberry-sbus/src/decoder/packet_decoder.s: raspberry-sbus/src/decoder/packet_decoder.c.s
.PHONY : raspberry-sbus/src/decoder/packet_decoder.s

# target to generate assembly for a file
raspberry-sbus/src/decoder/packet_decoder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/decoder/packet_decoder.c.s
.PHONY : raspberry-sbus/src/decoder/packet_decoder.c.s

raspberry-sbus/src/driver/SBUS.o: raspberry-sbus/src/driver/SBUS.cpp.o
.PHONY : raspberry-sbus/src/driver/SBUS.o

# target to build an object file
raspberry-sbus/src/driver/SBUS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/driver/SBUS.cpp.o
.PHONY : raspberry-sbus/src/driver/SBUS.cpp.o

raspberry-sbus/src/driver/SBUS.i: raspberry-sbus/src/driver/SBUS.cpp.i
.PHONY : raspberry-sbus/src/driver/SBUS.i

# target to preprocess a source file
raspberry-sbus/src/driver/SBUS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/driver/SBUS.cpp.i
.PHONY : raspberry-sbus/src/driver/SBUS.cpp.i

raspberry-sbus/src/driver/SBUS.s: raspberry-sbus/src/driver/SBUS.cpp.s
.PHONY : raspberry-sbus/src/driver/SBUS.s

# target to generate assembly for a file
raspberry-sbus/src/driver/SBUS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/driver/SBUS.cpp.s
.PHONY : raspberry-sbus/src/driver/SBUS.cpp.s

raspberry-sbus/src/tty/sbus_low_latency_linux.o: raspberry-sbus/src/tty/sbus_low_latency_linux.c.o
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_linux.o

# target to build an object file
raspberry-sbus/src/tty/sbus_low_latency_linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_low_latency_linux.c.o
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_linux.c.o

raspberry-sbus/src/tty/sbus_low_latency_linux.i: raspberry-sbus/src/tty/sbus_low_latency_linux.c.i
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_linux.i

# target to preprocess a source file
raspberry-sbus/src/tty/sbus_low_latency_linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_low_latency_linux.c.i
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_linux.c.i

raspberry-sbus/src/tty/sbus_low_latency_linux.s: raspberry-sbus/src/tty/sbus_low_latency_linux.c.s
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_linux.s

# target to generate assembly for a file
raspberry-sbus/src/tty/sbus_low_latency_linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_low_latency_linux.c.s
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_linux.c.s

raspberry-sbus/src/tty/sbus_low_latency_none.o: raspberry-sbus/src/tty/sbus_low_latency_none.c.o
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_none.o

# target to build an object file
raspberry-sbus/src/tty/sbus_low_latency_none.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_low_latency_none.c.o
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_none.c.o

raspberry-sbus/src/tty/sbus_low_latency_none.i: raspberry-sbus/src/tty/sbus_low_latency_none.c.i
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_none.i

# target to preprocess a source file
raspberry-sbus/src/tty/sbus_low_latency_none.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_low_latency_none.c.i
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_none.c.i

raspberry-sbus/src/tty/sbus_low_latency_none.s: raspberry-sbus/src/tty/sbus_low_latency_none.c.s
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_none.s

# target to generate assembly for a file
raspberry-sbus/src/tty/sbus_low_latency_none.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_low_latency_none.c.s
.PHONY : raspberry-sbus/src/tty/sbus_low_latency_none.c.s

raspberry-sbus/src/tty/sbus_tty_linux.o: raspberry-sbus/src/tty/sbus_tty_linux.c.o
.PHONY : raspberry-sbus/src/tty/sbus_tty_linux.o

# target to build an object file
raspberry-sbus/src/tty/sbus_tty_linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_tty_linux.c.o
.PHONY : raspberry-sbus/src/tty/sbus_tty_linux.c.o

raspberry-sbus/src/tty/sbus_tty_linux.i: raspberry-sbus/src/tty/sbus_tty_linux.c.i
.PHONY : raspberry-sbus/src/tty/sbus_tty_linux.i

# target to preprocess a source file
raspberry-sbus/src/tty/sbus_tty_linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_tty_linux.c.i
.PHONY : raspberry-sbus/src/tty/sbus_tty_linux.c.i

raspberry-sbus/src/tty/sbus_tty_linux.s: raspberry-sbus/src/tty/sbus_tty_linux.c.s
.PHONY : raspberry-sbus/src/tty/sbus_tty_linux.s

# target to generate assembly for a file
raspberry-sbus/src/tty/sbus_tty_linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/raspberry-sbus/src/tty/sbus_tty_linux.c.s
.PHONY : raspberry-sbus/src/tty/sbus_tty_linux.c.s

serialib.o: serialib.cpp.o
.PHONY : serialib.o

# target to build an object file
serialib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/serialib.cpp.o
.PHONY : serialib.cpp.o

serialib.i: serialib.cpp.i
.PHONY : serialib.i

# target to preprocess a source file
serialib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/serialib.cpp.i
.PHONY : serialib.cpp.i

serialib.s: serialib.cpp.s
.PHONY : serialib.s

# target to generate assembly for a file
serialib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/serialib.cpp.s
.PHONY : serialib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DroneController"
	@echo "... libsbus"
	@echo "... Connector.o"
	@echo "... Connector.i"
	@echo "... Connector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... raspberry-sbus/src/decoder/DecoderFSM.o"
	@echo "... raspberry-sbus/src/decoder/DecoderFSM.i"
	@echo "... raspberry-sbus/src/decoder/DecoderFSM.s"
	@echo "... raspberry-sbus/src/decoder/packet_decoder.o"
	@echo "... raspberry-sbus/src/decoder/packet_decoder.i"
	@echo "... raspberry-sbus/src/decoder/packet_decoder.s"
	@echo "... raspberry-sbus/src/driver/SBUS.o"
	@echo "... raspberry-sbus/src/driver/SBUS.i"
	@echo "... raspberry-sbus/src/driver/SBUS.s"
	@echo "... raspberry-sbus/src/tty/sbus_low_latency_linux.o"
	@echo "... raspberry-sbus/src/tty/sbus_low_latency_linux.i"
	@echo "... raspberry-sbus/src/tty/sbus_low_latency_linux.s"
	@echo "... raspberry-sbus/src/tty/sbus_low_latency_none.o"
	@echo "... raspberry-sbus/src/tty/sbus_low_latency_none.i"
	@echo "... raspberry-sbus/src/tty/sbus_low_latency_none.s"
	@echo "... raspberry-sbus/src/tty/sbus_tty_linux.o"
	@echo "... raspberry-sbus/src/tty/sbus_tty_linux.i"
	@echo "... raspberry-sbus/src/tty/sbus_tty_linux.s"
	@echo "... serialib.o"
	@echo "... serialib.i"
	@echo "... serialib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

